List<String> atasozu_liste = [
  "Abanın kadri yağmurda bilinir.",
  "Abdal abdalın ne umduğunu, ne bulduğunu ister.",
  "Abdal düğünden, çocuk oyundan usanmaz.",
  "Abdalın dostluğu köy görününceye kadardır.",
  "Abdalın karnı doyunca gözü yoldadır.",
  "Acele işe şeytan karışır.",
  "Acele yürüyen yolda kalır.",
  "Acı acıyı keser, su sancıyı.",
  "Acı patlıcanı kırağı çalmaz.",
  "Acıkan doymam, susayan kanmam sanır.",
  "Acıkan yanağından, susayan dudağından belli olur.",
  "Acıkmış kudurmuştan beterdir.",
  "Acın çekilmez, açın çekilir.",
  "Acında ne yemez, tokunda ne demez.",
  "Acıkanın karnında payı vardır.",
  "Aç ayı oynamaz.",
  "Aç bırakma hırsız edersin, çok söyleme arsız edersin.",
  "Aç doymam, tok acıkmam sanır.",
  "Aç domuz darıdan çıkmaz.",
  "Aç elini kora sokar.",
  "Aç gezmekten, tok ölmek yeğdir.",
  "Aç gözünü, açarlar gözünü.",
  "Aç karın katık istemez.",
  "Aç kurt aslana saldırır.",
  "Aç tavuk rüyasında darı görür.",
  "Aç tokun halinden anlamaz.",
  "Aç yanından kaç.",
  "Açın uykusu gelmez.",
  "Açın karnı doyar, gözü doymaz.",
  "Açık ağız aç kalmaz.",
  "Açık yaraya kurt düşmez.",
  "Açılan solar, ağlayan güler.",
  "Adam adamdır olmasa da pulu, eşek eşektir olsa da çulu.",
  "Adam adama yük değil, can gövdeye mülk değil.",
  "Adam adamdan korkmaz, utanır.",
  "Adam hacı mı olur ulaşmakla Mekke'ye, eşek derviş mi olur taş çekmekle tekkeye?",
  "Adam iş başında belli olur.",
  "Adam kıtlığında keçiye Abdurrahman Çelebi derler.",
  "Adam olana bir söz yeter.",
  "Adam yanıla yanıla, pehlivan yenile yenile.",
  "Adamın iyisi iş başında belli olur.",
  "Adet yerini bulsun diye.",
  "Ağaca balta vurmuşlar 'sapı bedenimden' demiş.",
  "Ağaca çıkan keçinin dala bakan oğlağı olur.",
  "Ağaç düşse de yakınına yaslanır.",
  "Ağaç kökünden yıkılır.",
  "Ağaç ne kadar uzasa göğe ermez.",
  "Ağaç yaşken eğilir.",
  "Ağaçtan maşa olmaz.",
  "Ağaran baş, ağlayan göz gizlenmez.",
  "Ağır basar, hafif kalkar.",
  "Ağır git ki yol alasın.",
  "Ağır kazan geç kaynar.",
  "Ağır taş Batman döver.",
  "Ağır taş yerinden oynamaz.",
  "Ağız yer, yüz utanır.",
  "Ağızdan çıkan söz, yaydan çıkan ok gibidir.",
  "Ağlama ölü için, ağla deli için.",
  "Ağlamayan çocuğa meme vermezler.",
  "Ağlarsa anam ağlar, kalanı yalan ağlar.",
  "Ağustosun yarısı yaz, yarısı kıştır.",
  "Ah alan onmaz, ah yerde kalmaz.",
  "Ahım şahım bir şey değil.",
  "Ahmak konuk ev sahibini ağırlar.",
  "Ak akçe kara gün içindir.",
  "Ak gün ağartır, kara gün karartır.",
  "Akıl akıldan üstündür.",
  "Akıl adama sermayedir.",
  "Akıl yaşta değil baştadır.",
  "Akıllı düşman cahil dosttan hayırlıdır.",
  "Akıllı köprü arayıncaya dek deli suyu geçer.",
  "Akılsız başın cezasını ayaklar çeker.",
  "Akılsız dostun olacağına akıllı düşmanın olsun.",
  "Akılsız kasabın gerisine kaçar masat.",
  "Akılsız köpeği yol kocatır.",
  "Akıncı ölür ama akın sürer.",
  "Akıntıya kürek çekilmez.",
  "Akşamın işini yarına bırakma.",
  "Al malın iyisini, çekme kaygısını.",
  "Al kaşağıyı gir ahıra, yarası olan gocunsun.",
  "Alacağına şahin, vereceğine karga.",
  "Alacağını bilmeyen, vereceğini düşünmez.",
  "Alışmış kudurmuştan beterdir.",
  "Alim unutmuş, kalem unutmamış.",
  "Allah bilir ama kul da sezer.",
  "Allah bir kapıyı kapatırsa öbürünü açar.",
  "Allah dağına göre kar verir.",
  "Allah doğrunun yardımcısıdır.",
  "Allah gümüş kapıyı kaparsa altın kapıyı açar.",
  "Allah sevdiği kulu darda bırakmaz.",
  "Almadığın hayvanı kuyruğundan tutma.",
  "Alna yazılan başa gelir.",
  "Altın anahtar her kapıyı açar.",
  "Altın eşik gümüş eşiğe muhtaç olur.",
  "Altın yere düşmekle değerini kaybetmez.",
  "Altının kıymetini sarraf bilir.",
  "Aman diyene kılıç kalkmaz.",
  "Anasına bak kızını al, kenarına bak bezini al.",
  "Anan güzel mi?",
  "Anan yahşi, baban yahşi.",
  "Anlatana değil, anlayana bak.",
  "Anlayana sivrisinek saz, anlamayana davul zurna az.",
  "Araba devrilince yol gösteren çok olur.",
  "Arayan mevlasını da bulur belasını da.",
  "Arefe günü yalan söyleyenin bayram günü yüzü kara çıkar.",
  "Arı bal alacak çiçeği bilir.",
  "Arife tarif gerekmez.",
  "Arkadaşını söyle ki kim olduğunu söyleyeyim.",
  "Armut dibine düşer.",
  "Armudun iyisini ayılar yer.",
  "Arpa eken buğday biçmez.",
  "Arpa samanıyla, adam zamanıyla.",
  "Asıl azmaz, bal kokmaz.",
  "Aslan yattığı yerden belli olur.",
  "Aslanın dişisi de aslandır.",
  "Astarı yüzünden pahalı.",
  "Aşk ağlatır, dert söyletir.",
  "Aşk başa gelirse akıl baştan gider.",
  "Aş taşınca kepçeye paha olmaz.",
  "At binenin kılıç kuşananındır.",
  "At ölür meydan kalır, yiğit ölür şan kalır.",
  "At sahibine göre kişner.",
  "At ver dert al.",
  "Atın ölümü arpadan olsun.",
  "Atın varken yol tanı, ağan varken el tanı.",
  "Atla katır tepişir, arada eşek ezilir.",
  "Atlar tepişir, eşekler arada kalır.",
  "Atlıya selam, yürüyene dua.",
  "Atmaca kuşu avlar, dumanı dağıtır.",
  "Ava giden avlanır.",
  "Avcı ne kadar hile bilse, ayı o kadar yol bilir.",
  "Ayakkabısı dar olan, dünyayı dar görür.",
  "Ayda bir gel dostuna, kalksın ayak üstüne.",
  "Ayıpsız dost arayan dostsuz kalır.",
  "Ayrılan kol bükülmez.",
  "Az tamah çok ziyan getirir.",
  "Az veren candan, çok veren maldan.",
  "Az yaşa, uz yaşa, akıbet gelecek başa.",
  "Azı bilmeyen çoğu hiç bilmez.",
  "Azıcık aşım, ağrısız başım.",
  "Azizim diyenin, gözü kör olsun.",
  "Baba malı tez tükenir, evlat gerek kazana.",
  "Babamın adı Hıdır, elimden gelen budur.",
  "Babasının hayrına mı?",
  "Bağ babadan, zeytin dededen kalmalı.",
  "Bağa bak üzüm olsun, yemeye yüzün olsun.",
  "Bağda izin olsun ki yemeye yüzün olsun.",
  "Bağla atını, ısmarla Hakka.",
  "Bahşiş atın dişine bakılmaz.",
  "Bakarsan bağ, bakmazsan dağ olur.",
  "Bakkal kazığı.",
  "Bal bal demekle ağız tatlanmaz.",
  "Bal tutan parmağını yalar.",
  "Balık baştan kokar.",
  "Bana benden olur her ne olursa, başım rahat eder dilim durursa.",
  "Bardağı taşıran son damladır.",
  "Basiret bağlanınca göz görmez olur.",
  "Baskın basanındır.",
  "Baş dille tartılır.",
  "Baş nereye giderse ayak da oraya gider.",
  "Başa gelen çekilir.",
  "Başın sağlığı, dünya varlığı.",
  "Başsız evde düzen olmaz.",
  "Batan güneş yeniden doğar.",
  "Bedava sirke baldan tatlıdır.",
  "Bekar gözüyle kız alınmaz.",
  "Bekarlık sultanlıktır.",
  "Bekleyen derviş muradına ermiş.",
  "Beleş peynir sadece fare kapanında bulunur.",
  "Belli düşman, gizli dosttan yeğdir.",
  "Ben ağa, sen ağa, bu ineği kim sağa?",
  "Ben derim bayramım, o der şalgamım.",
  "Benim oğlum bina okur, döner döner yine okur.",
  "Besle kargayı oysun gözünü.",
  "Beş parmağın beşi bir değil.",
  "Beterin beteri vardır.",
  "Beyazın adı var, esmerin tadı var.",
  "Bıçak kemiğe dayandı.",
  "Bıçak kendi sapını kesmez.",
  "Bilmemek ayıp değil, öğrenmemek ayıp.",
  "Bin bilsen de bir bilene danış.",
  "Bin dost az, bir düşman çok.",
  "Bin nasihatten bir musibet yeğdir.",
  "Bin ölçüp bir biçmeli.",
  "Bir acı kahvenin kırk yıl hatırı vardır.",
  "Bir ağaçla boran olmaz.",
  "Bir ağızdan çıkan, bin ağza yayılır.",
  "Bir baş soğana koca bir kazan bozulmaz.",
  "Bir çiçekle bahar gelmez.",
  "Bir çöplükte iki horoz ötmez.",
  "Bir elin nesi var, iki elin sesi var.",
  "Bir fincan kahvenin kırk yıl hatırı vardır.",
  "Bir görüş bir körlük, bir gülüş bir dert.",
  "Bir musibet bin nasihatten iyidir.",
  "Bir okla iki kuş vurulmaz.",
  "Bir sıçrarsın çekirge, iki sıçrarsın çekirge, üçüncüde yakalanırsın çekirge.",
  "Birlikten kuvvet doğar.",
  "Bitli baklanın kör alıcısı olur.",
  "Boğaz dokuz boğumdur.",
  "Bol bol yiyen, bel bel bakar.",
  "Borç yiğidin kamçısıdır.",
  "Boş çuval dik durmaz.",
  "Boş gezenin boş kalfası.",
  "Boş fıçı çok langırdar.",
  "Bugünkü işini yarına bırakma.",
  "Bugünkü tavuk yarınki kazdan iyidir.",
  "Bülbülü altın kafese koymuşlar, 'ah vatanım' demiş.",
  "Büyük balık küçük balığı yutar.",
  "Büyük lokma ye büyük söz söyleme.",
  "Can boğazdan gelir.",
  "Can çıkmadan huy çıkmaz.",
  "Can canın yoldaşıdır.",
  "Canı cana ölçmeli.",
  "Cefa çekmeyen sefanın kadrini bilmez.",
  "Cahilin dostluğundan alimin düşmanlığı yeğdir.",
  "Cami ne kadar büyük olsa da imam bildiğini okur.",
  "Canı yanan eşek atı geçer.",
  "Ceviz gölgesi, yavuz gölgesi.",
  "Cömert derler maldan ederler, yiğit derler candan ederler.",
  "Cahile laf anlatmak, deveye hendek atlatmaktan zordur.",
  "Çalışan demir pas tutmaz.",
  "Çam sakızı çoban armağanı.",
  "Çanakta ne varsa kaşığa o çıkar.",
  "Çantada keklik.",
  "Çatal kazık yere batmaz.",
  "Çay geçerken at değiştirilmez.",
  "Çıkmadık candan ümit kesilmez.",
  "Çiftçinin karnını yarmışlar, kırk tane 'gelecek yıl' çıkmış.",
  "Çiğ yemedim ki karnım ağrısın.",
  "Çivi çiviyi söker.",
  "Çoban kulübesinde padişah rüyası görmek.",
  "Çobansız koyunu kurt kapar.",
  "Çocuktan al haberi.",
  "Çok bilen çok yanılır.",
  "Çok gezen mi bilir, çok okuyan mı?",
  "Çok naz aşık usandırır.",
  "Çok söyleme arsız edersin, aç bırakma hırsız edersin.",
  "Çok söz yalansız, çok mal haramsız olmaz.",
  "Çürük tahta çivi tutmaz.",
  "Dağ dağa kavuşmaz, insan insana kavuşur.",
  "Dağ ne kadar yüce olsa yol üstünden aşar.",
  "Damlaya damlaya göl olur.",
  "Danışan dağı aşmış, danışmayanın yolu şaşmış.",
  "Darı unundan baklava, incir ağacından oklava olmaz.",
  "Davul dengi dengine çalar.",
  "Davulun sesi uzaktan hoş gelir.",
  "Değirmen iki taştan, muhabbet iki baştan.",
  "Deli deliyi görünce çomağını saklar.",
  "Deliye her gün bayram.",
  "Demir nemden, insan gamdan çürür.",
  "Demir tavında dövülür.",
  "Deniz dalgasız, gönül sevdasız olmaz.",
  "Denizdeki balığın pazarlığı olmaz.",
  "Denize düşen yılana sarılır.",
  "Dereyi görmeden paçaları sıvama.",
  "Derman arardım derdime, derdim bana derman imiş.",
  "Dert gezer, derman da gezer.",
  "Dert ağlatır, aşk söyletir.",
  "Deve boynundan büyük ot yerse boğazına takılır.",
  "Deve bir pula, deve bin pula.",
  "Deveyi yardan uçuran bir tutam ottur.",
  "Deveye 'boynun neden eğri?' demişler, 'nerem doğru ki?' demiş.",
  "Deveye hendek atlatmak, cahile laf anlatmaktan zordur.",
  "Devletli yanına varan sarınır, dertli yanına varan barınır.",
  "Dibi görünmeyen sudan geçme.",
  "Diken battığı yerden çıkar.",
  "Dilin kemiği yok ama kemiği kırar.",
  "Dilsiz ağzın dili var.",
  "Dinsizin hakkından imansız gelir.",
  "Dirlik nerede, devlet orada.",
  "Doğru sarsılır ama yıkılmaz.",
  "Doğru söyleyenin tepesi delik olur.",
  "Doğru söyleyeni dokuz köyden kovarlar.",
  "Dokuz ölç, bir biç.",
  "Dost acı söyler ama doğru söyler.",
  "Dost ağlatır, düşman güldürür.",
  "Dost başa bakar, düşman ayağa.",
  "Dost bini az, düşman biri çok.",
  "Dost dostun ayıbını yüzüne söyler.",
  "Dost kara günde belli olur.",
  "Dost sanma şanlı vaktinde dost olanı.",
  "Dost ile ye iç, alışveriş etme.",
  "Dut kurusuyla yârenlik olmaz.",
  "Dünya malı dünyada kalır.",
  "Dünyayı sel bassa ördeğe vız gelir.",
  "Düşenin dostu olmaz.",
  "Düşman düşmana rahmet okutur.",
  "Düşmanımın düşmanı dostumdur.",
  "Düşmez kalkmaz bir Allah.",
  "Ecel geldi cihana, baş ağrısı bahane.",
  "Ecele çare olmaz.",
  "Edebi edepsizden öğren.",
  "Eğilen baş kesilmez.",
  "Eğri cetvelden doğru çizgi çıkmaz.",
  "Eğri otur, doğru konuş.",
  "Ekmeden biçilmez.",
  "Ekmek aslanın ağzında.",
  "El ağzı fal açar.",
  "El elden üstündür, ta arşa kadar.",
  "El elin eşeğini türkü çağırarak arar.",
  "El elin aynasıdır.",
  "El için kuyu kazan, önce kendi düşer.",
  "El kazanıyla aş kaynamaz.",
  "El yumruğu yemeyen, kendi yumruğunu balyoz sanır.",
  "Elçiye zeval olmaz.",
  "Ele verir talkını, kendi yutar salkımı.",
  "Emanete hıyanet olmaz.",
  "Emek olmadan yemek olmaz.",
  "Emlakçıya ev, dula koca sorulmaz.",
  "En karlı yatırım, kendine yapılan yatırımdır.",
  "Er kemaliyle, avrat cemaliyle.",
  "Erken kalkan yol alır, er evlenen döl alır.",
  "Eski dost düşman olmaz, yenisinden vefa gelmez.",
  "Eski hamam eski tas.",
  "Eskiye rağbet olsa nur yağardı.",
  "Eşeğe altın semer vursalar, eşek yine eşektir.",
  "Eşeğini sağlam kazığa bağla, sonra Allah'a ısmarla.",
  "Eşek hoşaftan ne anlar?",
  "Et tırnaktan ayrılmaz.",
  "Ev alma komşu al.",
  "Evdeki hesap çarşıya uymaz.",
  "Evli evinde köylü köyünde gerek.",
  "Evvel can sonra canan.",
  "Ey iyilik, gel beni bul.",
  "Eğreti ata binen tez iner.",
  "Fakirlik ayıp değil, tembellik ayıp.",
  "Fare çıktığı deliği bilir.",
  "Fare delikten sığmamış, bir de kuyruğuna kabak bağlamış.",
  "Faydasız duaya amin denmez.",
  "Fazla mal göz çıkarmaz.",
  "Felek kimine kavun yedirir, kimine kelek.",
  "Fırsat her vakit ele geçmez.",
  "Fukaranın tavuğu tek tek yumurtlar.",
  "Gafil avlanmak.",
  "Garibin yardımcısı Allah'tır.",
  "Geç olsun da güç olmasın.",
  "Gelen gideni aratır.",
  "Gelene 'git' denmez.",
  "Gemisini kurtaran kaptandır.",
  "Gençlikte taş taşı, ihtiyarlıkta ye aşı.",
  "Gerçek dost kötü günde belli olur.",
  "Gez dünyayı, gör Konya'yı.",
  "Giren çıkan belli değil.",
  "Gitti gider, bir daha gelmez.",
  "Gitti ağalar, paşalar; şimdi kaldı köşeler.",
  "Gök ağlamayınca yer gülmez.",
  "Gönül bir hümadır, her dala konmaz.",
  "Gönül ferman dinlemez.",
  "Gönül kimi severse güzel odur.",
  "Gönül ummadığı yere küser.",
  "Gönülsüz yenen aş, ya karın ağrıtır ya baş.",
  "Görünen köy kılavuz istemez.",
  "Gözden ırak olan, gönülden de ırak olur.",
  "Göz gördüğünü ister.",
  "Göz görmeyince gönül katlanır.",
  "Gözü kör olsun.",
  "Gül dikensiz olmaz.",
  "Güle güle gidin.",
  "Gülme komşuna, gelir başına.",
  "Gülmekten kırılmak.",
  "Gülümseme sadakadır.",
  "Gümüş eşik, altın eşiğe muhtaç olur.",
  "Gün doğmadan neler doğar.",
  "Güneş balçıkla sıvanmaz.",
  "Güneş girmeyen eve doktor girer.",
  "Güvenme dostuna, saman doldurur postuna.",
  "Güvenme varlığa, düşersen darlığa.",
  "Güzel gittikçe çirkinleşir, çirkin gittikçe güzelleşir.",
  "Güzelin nazı çok olur.",
  "Haberi verenden değil, yapandan sor.",
  "Hacı hacıyı Mekke'de, derviş dervişi tekkede bulur.",
  "Haddini bilmek gibi irfan olmaz.",
  "Hak deyince akan sular durur.",
  "Hak yerini bulur.",
  "Halamın bıyığı olsa amcam olurdu.",
  "Hamala semeri yük değildir.",
  "Hamama giren terler.",
  "Hangi dağda kurt öldü?",
  "Haramın temeli olmaz.",
  "Harman döven öküzün ağzı bağlanmaz.",
  "Hasta yatan ölmez, eceli gelen ölür.",
  "Hastaya çorba sorulmaz.",
  "Hatasız kul olmaz.",
  "Haydan gelen huya gider.",
  "Hayır dile eşine, hayır gele başına.",
  "Hayırlı evlat neylesin malı, hayırsız evlat neylesin malı.",
  "Hazıra dağlar dayanmaz.",
  "He desen de bir, hi desen de.",
  "Hem suçlu hem güçlü.",
  "Her ağacın meyvesi olmaz.",
  "Her çok azdan olur.",
  "Her çiçek koklanmaz.",
  "Her düşüş bir öğreniş.",
  "Her horoz kendi çöplüğünde öter.",
  "Her işin başı sağlıktır.",
  "Her inişin bir yokuşu, her yokuşun bir inişi vardır.",
  "Her koyun kendi bacağından asılır.",
  "Her kuşun eti yenmez.",
  "Her sakallıyı baban sanma.",
  "Her şaka bir gerçek gizler.",
  "Her şey vaktini bekler.",
  "Her şeyin azı karar, çoğu zarar.",
  "Her şeyin yenisi, dostun eskisi.",
  "Her yiğidin bir yoğurt yiyişi vardır.",
  "Herkes ektiğini biçer.",
  "Herkes kendi kapısının önünü süpürse sokaklar temiz olur.",
  "Hıdırellez yaz kapısı, meyve tapusu.",
  "Hırsızın hiç mi suçu yok?",
  "Hızır gibi yetişmek.",
  "Horozu çok olan köyde sabah geç olur.",
  "Huy canın altındadır.",
  "Irmak kenarına çeşme yapılmaz.",
  "Isıracak köpek dişini göstermez.",
  "Isınmış aşın tadı olmaz.",
  "Ismarlama hac, hac olmaz.",
  "Işığını erken yakanın karanlığı çabuk gelir.",
  "İbadet de gizli, kabahat de.",
  "İğne atsan yere düşmez.",
  "İğneyi kendine, çuvaldızı başkasına batır.",
  "İki aslan bir posta sığmaz.",
  "İki baş bir kazanda kaynamaz.",
  "İki cambaz bir ipte oynamaz.",
  "İki çıplak bir hamama yakışır.",
  "İki el bir baş içindir.",
  "İki gönül bir olunca samanlık seyran olur.",
  "İki iyilik bir arada olmaz.",
  "İki karpuz bir koltuğa sığmaz.",
  "İki kişi dinden olursa, bir kişi candan olur.",
  "İkram izzetle olur.",
  "İlanı aşk etmek.",
  "İlerisini görmeyen, gerisini hiç görmez.",
  "İletişim dilin yarısıdır.",
  "İlgisiz dost, yabancıdan beterdir.",
  "İlim Çin'de de olsa gidip alınız.",
  "İlim kendin bilmektir.",
  "İmanlı it aç kalmaz.",
  "İnanma dostuna, saman doldurur postuna.",
  "İnatla murat hasıl olmaz.",
  "İneğin akı da süt, karası da.",
  "İnsan ayaktan, at tırnaktan düşer.",
  "İnsan çeşit çeşit, yer damar damar.",
  "İnsan doğduğu yerde değil, doyduğu yerdedir.",
  "İnsan insanın aynasıdır.",
  "İnsan insanın kurdu değil, umududur.",
  "İnsan kıymetini insan bilir.",
  "İnsan yedisinde neyse yetmişinde de odur.",
  "İnsana dayanma ölür, ağaca dayanma kurur.",
  "İnsanoğlu çiğ süt emmiştir.",
  "İp koptuğu yerden bağlanır.",
  "İsin yanına varan is, misin yanına varan mis kokar.",
  "İsteyenin bir yüzü kara, vermeyenin iki yüzü.",
  "İş bilenin, kılıç kuşananındır.",
  "İş insanın aynasıdır.",
  "İşten artmaz, dişten artar.",
  "İt iti ısırmaz.",
  "İt kağnı gölgesinde yürür de kendi gölgem sanırmış.",
  "İt ürür, kervan yürür.",
  "İyi dost kara günde belli olur.",
  "İyi evlat babayı vezir, kötü evlat rezil eder.",
  "İyi insan lafın üstüne gelir.",
  "İyi olacak hastanın doktor ayağına gelir.",
  "İyilik et denize at, balık bilmezse Halik bilir.",
  "İyilik eden iyilik bulur.",
  "İzinden gitmek.",
  "Kabahat samur kürk olsa kimse sırtına almaz.",
  "Kaçan balık büyük olur.",
  "Kadı anlatınca dinlenir.",
  "Kalp kalbe karşıdır.",
  "Kalıp kıyafetle adam olunmaz.",
  "Kanı kanla yumazlar, kanı suyla yurlar.",
  "Kapı açılırsa hırsız girer.",
  "Kara haber tez duyulur.",
  "Karanlıkta göz kırpmak.",
  "Kar kuytuda, para pintide eğleşir.",
  "Kâr ortaklığı, zarar ortalığı.",
  "Karnı tok, gönlü pek.",
  "Karun kadar zengin olmak.",
  "Kasap sevdiği postu yere vurur.",
  "Kaşıkla verip kepçeyle almak.",
  "Katranı kaynatsan olur mu şeker, cinsini sevdiğim cinsine çeker.",
  "Kaz gelen yerden tavuk esirgenmez.",
  "Kaza geliyorum demez.",
  "Kazancın yarısı tasarruftur.",
  "Keçi can derdinde, kasap yağ derdinde.",
  "Keçiye can kaygısı, kasaba yağ kaygısı.",
  "Kedi uzanamadığı ciğere mundar der.",
  "Kediye peynir tulumu ısmarlanmaz.",
  "Kel ölür sırma saçlı olur, kör ölür badem gözlü olur.",
  "Kendi düşen ağlamaz.",
  "Kendi göbeğini kendi kesmek.",
  "Keskin sirke küpüne zarar.",
  "Kırk yıllık yani, olur mu kani.",
  "Kırk gün taban eti, bir gün av eti.",
  "Kısmetinde ne varsa kaşığında o çıkar.",
  "Kızım sana söylüyorum, gelinim sen anla.",
  "Kimi yer kimi bakar, kıyamet ondan kopar.",
  "Kişi kendinden bilir işi.",
  "Kişi noksanını bilmek gibi irfan olmaz.",
  "Kişiyi nasıl bilirsin? Kendin gibi.",
  "Komşu komşunun külüne muhtaçtır.",
  "Komşu ekmeği komşuya borçtur.",
  "Korku dağları bekler.",
  "Korkunun ecele faydası yoktur.",
  "Koyun can derdinde, kasap et derdinde.",
  "Köpeksiz sürüye kurt iner.",
  "Köprüden geçene kadar ayıya dayı derler.",
  "Körle yatan şaşı kalkar.",
  "Körler sağırlar birbirini ağırlar.",
  "Kötü haber tez duyulur.",
  "Kötü komşu insanı ev sahibi yapar.",
  "Kurt kocayınca köpeklerin maskarası olur.",
  "Kurt dumanlı havayı sever.",
  "Kurunun yanında yaş da yanar.",
  "Kuş kanadıyla, er adıyla.",
  "Kuşu kuşla avlarlar.",
  "Kuzgunun yavrusu kendine şahin görünür.",
  "Küçük suda büyük balık olmaz.",
  "Külahıma anlat.",
  "Kürkçünün kürkü olmaz, terzinin söküğü.",
  "Laf lafı açar.",
  "Lafla peynir gemisi yürümez.",
  "Lafın azı, uzu çobana vermez kuzu.",
  "Leyi rızık, Allah kerim.",
  "Leyleğin ömrü laklakla geçer.",
  "Lokma çiğnenmeden yutulmaz.",
  "Lütuf bekleyen kapıda kalır.",
  "Mal canın yongasıdır.",
  "Malını yemeyenin malını yerler.",
  "Mart kapıdan baktırır, kazma kürek yaktırır.",
  "Mart ayı dert ayı.",
  "Maşa varken elini yakma.",
  "Mazlumun ahı, indirir şahı.",
  "Mekânın cennet olsun.",
  "Merd-i kıpti şecaat arz ederken sirkatin söyler.",
  "Mermer iyi taştan, iyilik iki baştan.",
  "Meyveli ağacı taşlarlar.",
  "Meyvesiz ağaca kimse taş atmaz.",
  "Minareyi çalan kılıfını hazırlar.",
  "Misafir kısmetiyle gelir.",
  "Misafir umduğunu değil bulduğunu yer.",
  "Mülk Allah'ındır.",
  "Mühür kimdeyse Süleyman odur.",
  "Müzik ruhun gıdasıdır.",
  "Namazda gözü olmayanın ezanda kulağı olmaz.",
  "Nasihat istersen ölüm yeter.",
  "Nazar adamı mezara, deveyi kazana sokar.",
  "Ne doğrarsan aşına, o gelir kaşığına.",
  "Ne ekersen onu biçersin.",
  "Ne karanlıkta yat, ne kara düş gör.",
  "Ne oldum dememeli, ne olacağım demeli.",
  "Ne verirsen elinle, o gelir seninle.",
  "Nerede hareket, orada bereket.",
  "Nereye gitsen rızkın seni bulur.",
  "Niyet hayır, akıbet hayır.",
  "O kedi buraya gelecek.",
  "Ocak başında oturmak.",
  "Oduncunun gözü oynaşta.",
  "Oğlan babadan öğrenir sofra açmayı, kız anadan öğrenir biçki biçmeyi.",
  "Ok yaydan çıktı.",
  "Okumayı sevmeyen, dünyayı görmez.",
  "Olacakla öleceğe çare bulunmaz.",
  "Olmaz olmaz deme, olmaz olmaz.",
  "On kere ölç, bir kere biç.",
  "Orman yağmurun anasıdır.",
  "Oturduğu ahır sekisi, çağırdığı İstanbul türküsü.",
  "Otuz iki dişten çıkan, otuz iki mahalleye yayılır.",
  "Öfke baldan tatlıdır.",
  "Öfkeyle kalkan zararla oturur.",
  "Öksüz kuzu toklu olmaz.",
  "Ölme eşeğim ölme, yonca bitecek.",
  "Ölmüş eşek kurttan korkmaz.",
  "Ölüm hak, miras helal.",
  "Ölümle öç alınmaz.",
  "Önce can, sonra canan.",
  "Önce iğneyi kendine batır, sonra çuvaldızı başkasına.",
  "Ön tekerlek nereye giderse arka tekerlek de oraya gider.",
  "Övünmek gibi olmasın.",
  "Öz ağlamayınca göz ağlamaz.",
  "Pahalıdır vardır bir hikmeti, ucuzdur vardır bir illeti.",
  "Papaz her zaman pilav yemez.",
  "Para parayı çeker.",
  "Parayı veren düdüğü çalar.",
  "Paran varsa cümle alem kulun, paran yoksa tımarhane yolun.",
  "Paşa gönlün bilir.",
  "Pazar ilkisinden, pazar ikisinden.",
  "Pekmez gibi malın olsun, sinek Bağdat'tan gelir.",
  "Pire için yorgan yakılmaz.",
  "Pironun hakkı piroya.",
  "Piliç kadar aklı yok.",
  "Pişmiş aşa su katılmaz.",
  "Rüzgar eken fırtına biçer.",
  "Rüzgara karşı tüküren kendi yüzüne tükürür.",
  "Rızkı veren Allah'tır.",
  "Sabahın hayrı akşamın şerrinden iyidir.",
  "Sabır acıdır, meyvesi tatlıdır.",
  "Sabır selamettir.",
  "Sabreden derviş muradına ermiş.",
  "Saç sefadan, tırnak cefadan uzar.",
  "Sağ elin verdiğini sol el görmesin.",
  "Sağlam kafa sağlam vücutta bulunur.",
  "Sakla samanı, gelir zamanı.",
  "Saman altından su yürütmek.",
  "Sanat altın bileziktir.",
  "Sana taşla vurana sen ekmekle vur.",
  "Sarımsağı gelin etmişler, kırk gün kokusu çıkmamış.",
  "Sayıla gelen bayram.",
  "Sebil etmek.",
  "Sel gider kum kalır.",
  "Sen ağa ben ağa, bu ineği kim sağa?",
  "Sermayen doğruluk olsun.",
  "Sert sirke küpüne zarar.",
  "Sev beni, seveyim seni.",
  "Seveceğin kulu Allah darda koymaz.",
  "Sevenin halinden seven anlar.",
  "Sevgi her engeli aşar.",
  "Seyreyle gümbürtüyü.",
  "Sıcak sütten ağzı yanan, ayranı üfleyerek içer.",
  "Sıkılmayan pazara gidemez.",
  "Sırrını söyleme dostuna, o da söyler dostuna.",
  "Sinek küçüktür ama mide bulandırır.",
  "Sirkesini, sarımsağını sayan paçayı yiyemez.",
  "Sokulgan köpek aç kalmaz.",
  "Son gülen iyi güler.",
  "Son pişmanlık fayda vermez.",
  "Sona kalan dona kalır.",
  "Soran yanılmamış.",
  "Sormak ayıp değil, bilmemek ayıp.",
  "Söyleyene değil, söyletene bak.",
  "Söz gümüşse sükut altındır.",
  "Söz namustur.",
  "Söz uçar, yazı kalır.",
  "Sözünü bil, pişir; ağzını der, devşir.",
  "Su akarken testiyi doldurmalı.",
  "Su akıntısına kürek çekilmez.",
  "Su bulandırmadan balık avlanmaz.",
  "Su testisi su yolunda kırılır.",
  "Su uyur düşman uyumaz.",
  "Su verenlerin çok olsun.",
  "Sus küçüğün, söz büyüğün.",
  "Susmak kabullenmektir.",
  "Suyu getiren de bir, testiyi kıran da.",
  "Sütten ağzı yanan ayranı üfleyerek içer.",
  "Sürüden ayrılanı kurt kapar.",
  "Şahin küçük ama koca kuşu indirir.",
  "Şahinle deve avlanmaz.",
  "Şamar oğlanına dönmek.",
  "Şapka düştü kel göründü.",
  "Şeytanın dostluğu ağaca çıkana kadardır.",
  "Şimşek çakmadan gök gürlemez.",
  "Şükür nimeti artırır.",
  "Talih adama gülmez, adam talihe güler.",
  "Tamahkarın gözünü bir avuç toprak doyurur.",
  "Tarlada izi olmayanın harmanda yüzü olmaz.",
  "Taşıma suyla değirmen dönmez.",
  "Taş yerinde ağırdır.",
  "Tatlı dil yılanı deliğinden çıkarır.",
  "Tavşan dağa küsmüş, dağın haberi olmamış.",
  "Tek elin nesi var, iki elin sesi var.",
  "Tek kanatla kuş uçmaz.",
  "Tekerlek kırıldıktan sonra yol gösteren çok olur.",
  "Tembele iş buyur, sana akıl öğretsin.",
  "Tencere yuvarlanmış kapağını bulmuş.",
  "Terzi kendi söküğünü dikemez.",
  "Teşbihte hata olmaz.",
  "Teyzesi defterdar, amcası mühürdar.",
  "Tilkinin dönüp dolaşacağı yer kürkçü dükkanıdır.",
  "Tok acın halinden anlamaz.",
  "Topal eşekle kervana karışılmaz.",
  "Toprağı işleyen ekmeği dişler.",
  "Ucuz etin yahnisi yavan olur.",
  "Ulu sözü dinlemeyen, uyur kalır.",
  "Uman dağlara kar yağar.",
  "Ummadığın taş baş yarar.",
  "Umut fakirin ekmeğidir.",
  "Uyuyan yılanın kuyruğuna basılmaz.",
  "Uzaktan davulun sesi hoş gelir.",
  "Ümit en son ölür.",
  "Üzüm üzüme baka baka kararır.",
  "Üzümünü ye, bağını sorma.",
  "Vakit nakittir.",
  "Var evi kerem evi, yok evi verem evi.",
  "Varda keramet vardır.",
  "Varışına göre gelişin, tarhanana göre bulgurun.",
  "Varlık barıştırır, yokluk dövüştürür.",
  "Varlığa güvenilmez.",
  "Veren el alan elden üstündür.",
  "Yabancı köpek kapıya gelmez.",
  "Ya devlet başa ya kuzgun leşe.",
  "Yağmurdan kaçarken doluya tutulmak.",
  "Yakın dost hayırsız hısımdan yeğdir.",
  "Yalan dolanla gemi yürümez.",
  "Yalan söyleyenin mumu yatsıya kadar yanar.",
  "Yalancının evi yanmış, kimse inanmamış.",
  "Yanlış hesap Bağdat'tan döner.",
  "Yap bir iyilik, at denize.",
  "Yara sıcakken sarılır.",
  "Yaralı kuşa kurşun sıkılmaz.",
  "Yarım elma gönül alma.",
  "Yarım hoca dinden, yarım doktor candan eder.",
  "Yarın ola hayır ola.",
  "Yastık değişir, kafa değişmez.",
  "Yaş kesen baş keser.",
  "Yatan aslandan gezen tilki yeğdir.",
  "Yalnız taş duvar olmaz.",
  "Yanlış hesap Bağdat'tan döner.",
  "Yananın yanında yatan da yanar.",
  "Yaprağına bak da ağacını anla.",
  "Yara sıcakken sarılır.",
  "Yaralı kuşa kurşun sıkılmaz.",
  "Yarım elma, gönül alma.",
  "Yarım hoca dinden, yarım doktor candan eder.",
  "Yarın ola hayır ola.",
  "Yastık değişir, kafa değişmez.",
  "Yaş kesen baş keser.",
  "Yaş yetmiş, iş bitmiş.",
  "Yaşın yanında kuru da yanar.",
  "Yatan aslandan gezen tilki yeğdir.",
  "Yatanın yürüyene borcu var.",
  "Yavuz hırsız ev sahibini bastırır.",
  "Yazın başı pişenin, kışın aşı pişer.",
  "Yazın gölge hoş, kışın çuval boş.",
  "Yedisinde ne ise yetmişinde de odur.",
  "Yel kayadan ne koparır?",
  "Yemeğin iyisi ette, sözün iyisi özte.",
  "Yenilen pehlivan güreşe doymaz.",
  "Yere bakan yürek yakan.",
  "Yerin kulağı vardır.",
  "Yılanın başı küçükken ezilir.",
  "Yılanın sevmediği ot, deliğinin ağzında biter.",
  "Yiğit bin yaşar, fırsat bir düşer.",
  "Yiğit lakabıyla anılır.",
  "Yiğidi öldür hakkını yeme.",
  "Yol sormakla bulunur.",
  "Yol yürümekle, borç ödemekle biter.",
  "Yolcu yolunda gerek.",
  "Yorganına göre uzat ayağını.",
  "Yumurtaya kulp takmak.",
  "Yuvayı yapan dişi kuştur.",
  "Yük altında ancak eşek kalır.",
  "Yüksek uçan alçak düşer.",
  "Yüz verme arsız olur, az verme hırsız olur.",
  "Zahmetsiz rahmet olmaz.",
  "Zaman her şeyin ilacıdır.",
  "Zaman sana uymazsa sen zamana uy.",
  "Zemheri zürefası.",
  "Zengin arabasını dağdan aşırır, züğürt düz ovada yolunu şaşırır.",
  "Zenginin horozu bile yumurtlar.",
  "Zenginin malı züğürdün çenesini yorar.",
  "Zeytinyağı gibi üste çıkmak.",
  "Ziyanın neresinden dönülse kârdır.",
  "Zor kapıdan girerse, şer bacadan çıkar.",
  "Zorla güzellik olmaz.",
  "Zulüm ile abad olanın akıbeti berbat olur.",
  "Abanın kadri yağmurda bilinir.",
  "Acıkan doymam, susayan kanmam sanır.",
  "Aç tavuk rüyasında darı görür.",
  "Akıl akıldan üstündür.",
  "Alçak yerin tepeciği dağ görünür.",
  "Altın eşik, gümüş eşiğe muhtaç olur.",
  "Arayan mevlasını da bulur, belasını da.",
  "Arpa eken buğday biçmez.",
  "Aslan yattığı yerden belli olur.",
  "At ölür meydan kalır, yiğit ölür şan kalır.",
  "Ateş olmayan yerden duman çıkmaz.",
  "Azıcık aşım, kaygısız başım.",
  "Bakarsan bağ, bakmazsan dağ olur.",
  "Bal tutan parmağını yalar.",
  "Balık baştan kokar.",
  "Baş nereye giderse, ayak da oraya gider.",
  "Besle kargayı oysun gözünü.",
  "Beterin beteri vardır.",
  "Bilmemek ayıp değil, öğrenmemek ayıp.",
  "Bin bilsen de bir bilene danış.",
  "Bir elin nesi var, iki elin sesi var.",
  "Bir musibet bin nasihatten iyidir.",
  "Boş çuval dik durmaz.",
  "Bugünkü işini yarına bırakma.",
  "Büyük lokma ye, büyük söz söyleme.",
  "Can boğazdan gelir.",
  "Can çıkmadan huy çıkmaz.",
  "Çalışan demir pas tutmaz.",
  "Çivi çiviyi söker.",
  "Çok bilen çok yanılır.",
  "Çok gezen çok bilir.",
  "Dağ dağa kavuşmaz, insan insana kavuşur.",
  "Damlaya damlaya göl olur.",
  "Davulun sesi uzaktan hoş gelir.",
  "Demir tavında dövülür.",
  "Denize düşen yılana sarılır.",
  "Dereyi görmeden paçaları sıvama.",
  "Dinsizin hakkından imansız gelir.",
  "Doğru söyleyeni dokuz köyden kovarlar.",
  "Dost kara günde belli olur.",
  "Düşenin dostu olmaz.",
  "Eğri oturup doğru konuşalım.",
  "Ekmeğin büyüğü, hamurun çoğundan olur.",
  "El elden üstündür.",
  "El için kuyu kazan önce kendi düşer.",
  "Emek olmadan yemek olmaz.",
  "Eski dost düşman olmaz.",
  "Eşeğini sağlam kazığa bağla.",
  "Ev alma komşu al.",
  "Evdeki hesap çarşıya uymaz.",
  "Fazla mal göz çıkarmaz.",
  "Gelen gideni aratır.",
  "Geç olsun da güç olmasın.",
  "Gemisini kurtaran kaptandır.",
  "Görünen köy kılavuz istemez.",
  "Gözden ırak olan gönülden de ırak olur.",
  "Gülme komşuna gelir başına.",
  "Güneş balçıkla sıvanmaz.",
  "Güneş girmeyen eve doktor girer.",
  "Güvenme varlığa, düşersin darlığa.",
  "Hamama giren terler.",
  "Hatasız kul olmaz.",
  "Haydan gelen huya gider.",
  "Hazıra dağlar dayanmaz.",
  "Her horoz kendi çöplüğünde öter.",
  "Her işte bir hayır vardır.",
  "Her koyun kendi bacağından asılır.",
  "Her kuşun eti yenmez.",
  "Her şeyin başı sağlıktır.",
  "Her yiğidin bir yoğurt yiyişi vardır.",
  "Irmaktan geçerken at değiştirilmez.",
  "Isıracak köpek dişini göstermez.",
  "İğneyi kendine, çuvaldızı başkasına batır.",
  "İki aslan bir posta sığmaz.",
  "İki cambaz bir ipte oynamaz.",
  "İki gönül bir olunca samanlık seyran olur.",
  "İyilik et denize at, balık bilmezse Halik bilir.",
  "İşleyen demir ışıldar.",
  "İt ürür kervan yürür.",
  "Kaçan balık büyük olur.",
  "Kalp kalbe karşıdır.",
  "Kendi düşen ağlamaz.",
  "Keskin sirke küpüne zarar.",
  "Kızım sana söylüyorum, gelinim sen anla.",
  "Komşu komşunun külüne muhtaçtır.",
  "Korkunun ecele faydası yoktur.",
  "Körle yatan şaşı kalkar.",
  "Kötü komşu insanı mal sahibi yapar.",
  "Kurunun yanında yaş da yanar.",
  "Laf ile peynir gemisi yürümez.",
  "Mal canın yongasıdır.",
  "Mart kapıdan baktırır, kazma kürek yaktırır.",
  "Meyve veren ağaç taşlanır.",
  "Minareyi çalan kılıfını hazırlar.",
  "Misafir umduğunu değil bulduğunu yer.",
  "Ne ekersen onu biçersin.",
  "Nerede hareket, orada bereket.",
  "Öfke ile kalkan zararla oturur.",
  "Para parayı çeker.",
  "Parayı veren düdüğü çalar.",
  "Rüzgar eken fırtına biçer.",
  "Sabır acıdır ama meyvesi tatlıdır.",
  "Sabreden derviş muradına ermiş.",
  "Sakla samanı gelir zamanı.",
  "Sona kalan dona kalır.",
  "Söz gümüşse sükut altındır.",
  "Su uyur düşman uyumaz.",
  "Sütten ağzı yanan ayranı üfleyerek içer.",
  "Tatlı dil yılanı deliğinden çıkarır.",
  "Taşıma suyla değirmen dönmez.",
  "Tavşan dağa küsmüş dağın haberi olmamış.",
  "Tencere yuvarlanmış kapağını bulmuş.",
  "Terzi kendi söküğünü dikemez.",
  "Tilkinin dönüp dolaşacağı yer kürkçü dükkanıdır.",
  "Ucuz etin yahnisi yavan olur.",
  "Ummadığın taş baş yarar.",
  "Umut fakirin ekmeğidir.",
  "Üzüm üzüme baka baka kararır.",
  "Vakit nakittir.",
  "Veren el alan elden üstündür.",
  "Yalan söyleyenin mumu yatsıya kadar yanar.",
  "Yanlış hesap Bağdat'tan döner.",
  "Yarınki tavuktan bugünkü yumurta yeğdir.",
  "Yazın başı pişenin kışın aşı pişer.",
  "Yerin kulağı vardır.",
  "Yılanın sevmediği ot deliğinin ağzında biter.",
  "Yolcu yolunda gerek.",
  "Yorganına göre ayak uzat.",
  "Yuvayı yapan dişi kuştur.",
  "Zahmetsiz rahmet olmaz.",
  "Zararın neresinden dönülse kardır.",
  "Zengin arabasını dağdan aşırır.",
  "Zorla güzellik olmaz.",
  "Ak akçe kara gün içindir.",
  "Aç kalmak alçalmaktan hayırlıdır.",
  "Acele işe şeytan karışır.",
  "Ağaç yaşken eğilir.",
  "Ağlamayan çocuğa meme vermezler.",
  "Akan su yosun tutmaz.",
  "Akıllı düşman cahil dosttan hayırlıdır.",
  "Akılsız başın cezasını ayaklar çeker.",
  "Alışmış kudurmuştan beterdir.",
  "Altının kıymetini sarraf bilir.",
  "Araba devrilince yol gösteren çok olur.",
  "Arkadaşını söyle ki kim olduğunu söyleyeyim.",
  "Armut dibine düşer.",
  "Atasözü tutmayan, yabana atılır.",
  "Ateş düştüğü yeri yakar.",
  "Ava giden avlanır.",
  "Ayakkabısı dar olan dünyayı dar görür.",
  "Ayağını yorganına göre uzat.",
  "Az tamah çok ziyan getirir.",
  "Az veren candan, çok veren maldan.",
  "Bağa bak üzüm olsun, yemeye yüzün olsun.",
  "Bakarsan bağ, bakmazsan dağ olur.",
  "Bal bal demekle ağız tatlanmaz.",
  "Başın sağlığı, dünya varlığı.",
  "Bedava sirke baldan tatlıdır.",
  "Bir çiçekle bahar gelmez.",
  "Birlikten kuvvet doğar.",
  "Borç yiğidin kamçısıdır.",
  "Bugünkü tavuk yarınki kazdan iyidir.",
  "Bülbülü altın kafese koymuşlar 'ah vatanım' demiş.",
  "Büyük balık küçük balığı yutar.",
  "Can canın yoldaşıdır.",
  "Cömert derler maldan ederler, yiğit derler candan ederler.",
  "Çam sakızı çoban armağanı.",
  "Çıkmadık candan ümit kesilmez.",
  "Çoban kulübesinde padişah rüyası görmek.",
  "Çobansız koyunu kurt kapar.",
  "Çocuktan al haberi.",
  "Çürük tahta çivi tutmaz.",
  "Dağ ne kadar yüce olsa yol üstünden aşar.",
  "Darı unundan baklava olmaz.",
  "Deliye her gün bayram.",
  "Demir nemden, insan gamdan çürür.",
  "Deniz dalgasız, gönül sevdasız olmaz.",
  "Diken battığı yerden çıkar.",
  "Dilin kemiği yok ama kemiği kırar.",
  "Dünya malı dünyada kalır.",
  "Düşmanımın düşmanı dostumdur.",
  "Düşmez kalkmaz bir Allah.",
  "Ecel geldi cihana, baş ağrısı bahane.",
  "Eğilen baş kesilmez.",
  "Ekmek aslanın ağzında.",
  "El elin aynasıdır.",
  "El yumruğu yemeyen kendi yumruğunu balyoz sanır.",
  "En karlı yatırım kendine yapılan yatırımdır.",
  "Eskiye rağbet olsa nur yağardı.",
  "Eşeğe altın semer vursalar eşek yine eşektir.",
  "Et tırnaktan ayrılmaz.",
  "Gez dünyayı gör Konya'yı.",
  "Gök ağlamayınca yer gülmez.",
  "Gönül ferman dinlemez.",
  "Gönül kimi severse güzel odur.",
  "Göz görmeyince gönül katlanır.",
  "Gül dikensiz olmaz.",
  "Gün doğmadan neler doğar.",
  "Güzelin nazı çok olur.",
  "Hak deyince akan sular durur.",
  "Hamala semeri yük değildir.",
  "Hatasız kul olmaz.",
  "Hem suçlu hem güçlü.",
  "Her ağacın meyvesi olmaz.",
  "Her çok azdan olur.",
  "Her çiçek koklanmaz.",
  "Her şaka bir gerçek gizler.",
  "Hırsızın hiç mi suçu yok?",
  "Huy canın altındadır.",
  "İğne atsan yere düşmez.",
  "İki baş bir kazanda kaynamaz.",
  "İki iyilik bir arada olmaz.",
  "İki karpuz bir koltuğa sığmaz.",
  "İkram izzetle olur.",
  "İlim kendin bilmektir.",
  "İnsan kıymetini insan bilir.",
  "İp koptuğu yerden bağlanır.",
  "İş insanın aynasıdır.",
  "İşten artmaz dişten artar.",
  "İyi insan lafın üstüne gelir.",
  "Kaderde ne varsa o gelir başa.",
];
